version: '3.4'

services:
  multiapp:
    image: natymony/examultiapp:dev
    container_name: MultiApp
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "MultiApp"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_multiapp$
    volumes:
      - D:\MAESTRIA\automatizacion\Examen1\MultiApp\MultiApp:/app
      - D:\MAESTRIA\automatizacion\Examen1\MultiApp:/src
      - C:\Users\natym\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_multiapp$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_multiapp$ \"/src/../../Taller_3/MultiApp/MultiApp/bin/Debug/net6.0/MultiApp.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  webapi:
    image: natymony/exawebapi:dev
    container_name: WebApi
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webapi$
    volumes:
      - D:\MAESTRIA\automatizacion\Examen1\MultiApp\WebApi:/app
      - D:\MAESTRIA\automatizacion\Examen1\MultiApp:/src
      - C:\Users\natym\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_webapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webapi$ \"/src/../../Taller_3/MultiApp/WebApi/bin/Debug/net6.0/WebApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
