// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using WebApi.DTO;
using WebApi.Model;
using Microsoft.EntityFrameworkCore;
using WebApi.DTO;
using WebApi.Model;

namespace WebApi.Data
{
    public partial class AdapterDbContext : DbContext
    {
        public AdapterDbContext()
        {
        }

        public AdapterDbContext(DbContextOptions<AdapterDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<persona> Persona { get; set; }
        public virtual DbSet<factura> Factura { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<persona>(entity =>
            {
                entity.Property(e => e.cedula)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.apellido)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.direccion)
                   .IsRequired()
                   .HasMaxLength(300)
                   .IsUnicode(false);

                entity.Property(e => e.telefono)
                 .IsRequired()
                 .HasMaxLength(10)
                 .IsUnicode(false);
            });

            modelBuilder.Entity<FacturaDto>().Property(p => p.numero)
            .ValueGeneratedOnAdd();
            modelBuilder.Entity<factura>(entity =>
            {

                entity.Property(e => e.fecha)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.valor)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.descripcion)
                   .IsRequired()
                   .HasMaxLength(300)
                   .IsUnicode(false);
            });




            OnModelCreatingPartial(modelBuilder);

           

        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}